version: 2
updates:
  - package-ecosystem: github-actions
    directories:
      - "/"
      - ".github/actions/eclint"
      - ".github/actions/prepare-for-build"
    open-pull-requests-limit: 25
    schedule:
      interval: monthly
    commit-message:
      prefix: ci
    labels: [dependencies, skip-changelog]
    cooldown:
      default-days: 7

  # python dependencies in /dev-tools/scripts
  - package-ecosystem: pip
    directory: /dev-tools/scripts/
    open-pull-requests-limit: 25
    schedule:
      interval: monthly
    commit-message:
      prefix: build(deps)
    labels: [dependencies, skip-changelog]
    cooldown:
      default-days: 7

  - package-ecosystem: gradle
    directory: /
    open-pull-requests-limit: 25
    schedule:
      interval: weekly
      day: tuesday
    commit-message:
      prefix: deps(java)
    labels: [dependencies, skip-changelog]
    cooldown:
      default-days: 7
