name: Gradle Precommit Checks

on: 
  pull_request:
    branches:
    - '*'

  push:
    branches:
    - main
    - branch_9x

jobs:
  # This runs all validation checks without tests.
  checks:
    name: gradle check -x test (JDK ${{ matrix.java }} on ${{ matrix.os }})
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        # Operating systems to run on.
        os: [ubuntu-latest]
        # Test JVMs.
        java: [ '17' ]

    steps:
    - uses: actions/checkout@v2

    - name: Set up JDK
      uses: actions/setup-java@v2
      with:
        distribution: 'temurin'
        java-version: ${{ matrix.java }}
        java-package: jdk

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - uses: actions/cache@v2
      with:
        path: |
          ~/.gradle/caches
        key: ${{ runner.os }}-gradle-precommit-${{ hashFiles('versions.lock') }}
        restore-keys: |
          ${{ runner.os }}-gradle-precommit-
          ${{ runner.os }}-gradle-

    - name: Initialize gradle settings
      run: ./gradlew localSettings --max-workers 2

    - name: Run gradle check (without tests)
      run: ./gradlew check -x test -Ptask.times=true --max-workers 2

    # - uses: gradle/wrapper-validation-action@v1

  # This runs all tests without any other validation checks.
  tests:
    name: gradle test (JDK ${{ matrix.java }} on ${{ matrix.os }})
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        # Operating systems to run on.
        # windows-latest: fairly slow to build and results in odd errors (see LUCENE-10167)
        # macos-latest: a tad slower than ubuntu and pretty much the same (?) so leaving out.
        os: [ubuntu-latest]
        # Test JVMs.
        java: [ '17' ]

    steps:
    - uses: actions/checkout@v2

    - name: Set up JDK
      uses: actions/setup-java@v2
      with:
        distribution: 'temurin'
        java-version: ${{ matrix.java }}
        java-package: jdk

    - uses: actions/cache@v2
      with:
        path: |
          ~/.gradle/caches
        key: ${{ runner.os }}-gradle-precommit-${{ hashFiles('versions.lock') }}
        restore-keys: |
          ${{ runner.os }}-gradle-precommit-
          ${{ runner.os }}-gradle-

    - name: Initialize gradle settings
      run: ./gradlew localSettings --max-workers 2

    - name: Echo settings
      run: cat gradle.properties

    - name: Run gradle tests
      run: ./gradlew test "-Ptask.times=true" "-Ptests.slow=false" --max-workers 2

    # - uses: gradle/wrapper-validation-action@v1
